image: jangrewe/gitlab-ci-android
before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
stages:
  - build
  - test
  - deploy
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/
assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
unitTest:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebugUnitTest
  artifacts:
    expire_in: 7 days
    paths:
      - app/build/reports/tests/testDebugUnitTest/
pages:
  stage: deploy
  script:
    - mv app/build/reports/tests/testDebugUnitTest/ public
  artifacts:
    expire_in: 7 days
    paths:
      - public