image: seanghay/android-ci
before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
stages:
  - build
  - test
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/
assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
unitTest:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebugUnitTest
  artifacts:
    expire_in: 7 days
    paths:
      - app/build/reports/tests/testDebugUnitTest/