# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Release Build"
  lane :beta do
    gradle(task: "clean assembleRelease")  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Distribute"
  lane :distribute do
        gradle(
  	  task: "assemble",
  	  build_type: "Release"
	)
        # build_android_app is a built-in fastlane action.
        firebase_app_distribution(
            app: "1:1026274536055:android:acf843e337cf9b7ccaf472",
	    firebase_cli_token: "4/1AX4XfWi-lIpsTtmi1fS2yXpy1ipAXBfP32m0ryewicoDUO5o-GFOeeP0nAo",
            testers: "antonyleons29@gmail.com",
            release_notes: "Lots of amazing new features to test out!"
        )
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
