# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  	desc "Runs all the tests"
  	lane :test do
    		gradle(task: "test", build_type: "Release")
  	end
	
	desc "Lint check"
	lane :lint do
		gradle(task: "lint", build_type: "Release")
	end

  	desc "Build and Distribute"
  	lane :distribute do
		gradle(task: "clean")
        	gradle(task: "assemble", build_type: "Debug")
        	# build_android_app is a built-in fastlane action.
#         	firebase_app_distribution(
#             		app: "1:1026274536055:android:acf843e337cf9b7ccaf472",
# 	    		firebase_cli_token: "1//0g7SYzdCDXMVcCgYIARAAGBASNwF-L9Ir5dLILC4Iz1GnlcBRJf_qpuUj2pXydiL3-Du-BgUoASyJ-7GURFrb3AJet8WOdwaPakk",
#             		testers: "antonyleons29@gmail.com",
#             		release_notes: "Lots of amazing new features to test out!"
#         	) 
    	end
end
