name: Build
on: [pull_request, push]
jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"

  lintCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Check lint
        run: ./gradlew lintDebug
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run unit test
        run: ./gradlew test