name: Build
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: sudo chmod -R a+w /var
      - name: Install bundler
        run: gem install bundler
      - name: Bundle install dependencies
        run: bundle install --quiet
      - name: Bundle update dependencies
        run: bundle update --quiet
      - name: Lint with fastlane
        run: bundle exec fastlane lint
