name: Build
on: [pull_request, push]
jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew assembleDebug
  lintCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check lint
        run: ./gradlew lintDebug
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test
        run: ./gradlew test