name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Android Cache
        uses: actions/cache@v2
        with:
          path: ~/.android/build-cache
          key: android-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
          android-${{ runner.os }}-
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew assembleDebug --build-cache
      - name: Run unit test
        run: ./gradlew test --build-cache