name: Build
on: [pull_request, push]
jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew assembleDebug
        with:
          apk: app/build/outputs/apk/debug/app_debug.apk

  lintCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Check lint
        run: ./gradlew lintDebug
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run unit test
        run: ./gradlew test